In [55]:
import xarray as xr
import numpy as np
from atl_module import load_netcdf, icesat_bathymetry

In [56]:
beamdata = load_netcdf.load_beam_array_ncds(
    "../data/test_sites/florida_keys/ATL03/processed_ATL03_20181017085235_02860107_005_01.nc",
    "gt2l",
)

In [113]:
df = icesat_bathymetry.add_along_track_dist(beamdata).set_index("dist_or")

In [115]:
df.Z_geoid.index

Float64Index([               0.0,  2.128887001757232, 16.394205669232978,
               20.67182815739219, 42.057372845160934,  44.19518071829066,
               54.88188612726716, 56.306690845268385,  72.68412392505059,
               73.39579415629218,
              ...
              17012.535948647124, 17013.961841374046,  17014.67099111373,
              17017.515577670867, 17018.222039418582,  17023.20191906939,
              17023.908303009914, 17023.912013495672, 17023.912098123565,
              17026.750843638278],
             dtype='float64', name='dist_or', length=12139)

In [141]:
def printfunc(series_in):
    center_loc = series_in.index[int(len(series_in) / 2)]
    # print(center_loc)
    window_distance = 100
    min_periods = 50
    series_in = series_in[
        (series_in.index > center_loc - window_distance / 2)
        & (series_in.index < center_loc + window_distance / 2)
    ]
    # print(series_in)
    if len(series_in) >= min_periods:
        return series_in.count()
    else:
        return np.NaN


out = df.Z_geoid.rolling(
    window=201,
    center=True,
).apply(printfunc)

In [83]:
ds = df.set_index("dist_or").to_xarray()

In [84]:
rolling_result = ds.rolling(dim={"dist_or": 200}, center=True)

In [85]:
for lablel, x in rolling_result:
    print(x)

TypeError: 'DatasetRolling' object is not iterable

In [73]:
dist_count = rolling_result.Z_geoid.to_pandas()

In [74]:
dist_count

newdim,0,1,2,3,4,5,6,7,8,9,...,190,191,192,193,194,195,196,197,198,199
dist_or,,,,,,,,,,,,,,,,,,,,,
0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.722635,0.231274,0.389816,19.135723,-0.195536,0.189024,0.145025,0.176378,0.123665,0.068520
2.128887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.231274,0.389816,19.135723,-0.195536,0.189024,0.145025,0.176378,0.123665,0.068520,0.167614
16.394206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.389816,19.135723,-0.195536,0.189024,0.145025,0.176378,0.123665,0.068520,0.167614,0.006557
20.671828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,19.135723,-0.195536,0.189024,0.145025,0.176378,0.123665,0.068520,0.167614,0.006557,-0.015104
42.057373,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,-0.195536,0.189024,0.145025,0.176378,0.123665,0.068520,0.167614,0.006557,-0.015104,-0.483656
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17023.201919,-0.130596,0.065702,0.135765,0.073254,0.024649,-0.354895,-3.913952,0.060568,-4.264809,-0.090416,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17023.908303,0.065702,0.135765,0.073254,0.024649,-0.354895,-3.913952,0.060568,-4.264809,-0.090416,-0.041439,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17023.912013,0.135765,0.073254,0.024649,-0.354895,-3.913952,0.060568,-4.264809,-0.090416,-0.041439,-0.038313,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17023.912098,0.073254,0.024649,-0.354895,-3.913952,0.060568,-4.264809,-0.090416,-0.041439,-0.038313,-0.124004,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17026.750844,0.024649,-0.354895,-3.913952,0.060568,-4.264809,-0.090416,-0.041439,-0.038313,-0.124004,0.075104,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN